######## Register
POST https://coursani.herokuapp.com/api/auth/register
Content-Type: application/json

{
    "username": "Pham Quang Thien",
    "password": "123456"
}

################################ Login
POST https://coursani.herokuapp.com/api/auth/login
Content-Type: application/json

{
    "username": "Pham Quang Thien",
    "password": "123456"
}

######## post Create new course
POST https://coursani.herokuapp.com/api/course/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiODU5MWQwOGJhNzM2MzQ0ZjhmNTciLCJpYXQiOjE2MjkxOTM2NzV9.JhpfrtgBzswH6KlfhaKdSaG5YR3iglCJS7EcWxb9WKk

{
    "title": "Hoc VueX ",
    "description": "Khoa hoc VueX",
    "url": "https://vi.vuejs.org/"
}
######## get list course 
GET https://coursani.herokuapp.com/api/course/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiODU5MWQwOGJhNzM2MzQ0ZjhmNTciLCJpYXQiOjE2MjkxOTM2NzV9.JhpfrtgBzswH6KlfhaKdSaG5YR3iglCJS7EcWxb9WKk

######## put 
PUT http://localhost:5000/api/course/6119cde5a7682b1e4c2677ca
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE5YmQ3NWJhYWY4ZDJmYWNhYWQwYjciLCJpYXQiOjE2MjkwNzY4ODl9.yXsC34bcL0t0RCNpxFnCctnA83t1xOSmYJfcyuV6_wk

{
    "title": "Hoc JS",
    "description": "Khoa hoc JS",
    "url": "https://fb.com",
    "state": "DOING"
}
######## put 
DELETE http://localhost:5000/api/course/6119cdd1a7682b1e4c2677c6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE5YmQ3NWJhYWY4ZDJmYWNhYWQwYjciLCJpYXQiOjE2MjkwNzY4ODl9.yXsC34bcL0t0RCNpxFnCctnA83t1xOSmYJfcyuV6_wk
